encoding: utf-8
title: 殷东亮的博客
email: tcitry@gmail.com
keywords: [殷东亮, 后端, Linux, Python, Mac, iOS]
description: "yindongliang's blog"
url: 'http://yindongliang.com'
timezone: Asia/Shanghai
permalink: /:title
highlighter: rouge
gems: [jekyll-paginate]
paginate: 50
IMG_PATH: http://yindl.qiniudn.com
markdown: kramdown
exclude: ['media', 'update.lftp', 'pushbaidu.sh', '.htaccess', "LICENSE", "README.md", "CNAME", "vendor", "Gemfile"]
sass:
  sass_dir: _sass
  style: :compressed
kramdown: 
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
defaults:
  -
    scope:
      path: '_posts'
      type: posts 
    values:
      is_post: true