# General Jekyll Config
highlighter: rouge
url: http://yindongliang.com
title: 殷东亮的博客
author: Dongliang Yin
email: tcitry@gmail.com
description: Dongliang Yin's Blog | 殷东亮的博客
simple_search: https://www.google.com/search
lsi: false
disqus: yindongliang
permalink: /:year/:month/:day/:title/
category_dir: blog/categories
paginate: 2
paginate_path: "page:num"
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]